Allow source cluster without mirroring feature
I tried to set up a replication flow from a cluster on the stock Kafka 4.1.1 (which obviously doesn't have the new feature) to a cluster on this code. When I start replication of a topic, the logs will have

```
[2026-05-05 13:52:47,132] WARN [MirrorCoordinator id=1] Failed to truncate to last mirrored offsets for mirror my-mirror, retrying in 5000 ms (kafka.server.mirror.MirrorCoordinator)
org.apache.kafka.common.errors.UnsupportedVersionException: The node does not support DESCRIBE_MIRRORS
```

and the partitions of the topic will all stay in `PREPARING`.

I don't think what's in this PR now is a proper fix. But to make one, I need to understand how it is supposed to work when the source cluster is an older Kafka without the `DESCRIBE_MIRRORS` API. Could you please help me?